"""
Deploy Proxmox management agent to BananaPi (banapi) at 192.168.0.134.

What this does:
  1. Uploads all agent source files to /home/pi/proxmox-agent/
  2. Copies SSH keys from D:\\SSH Keys\\ to ~/.proxmox-agent/keys/ on the Pi
  3. Writes a Pi-configured .env (SSH_KEYS_DIR pointing to Pi path)
  4. Creates a Python venv and installs dependencies
  5. Installs a systemd service (proxmox-agent-headless) for cron/no-LLM mode
  6. Does NOT touch the existing assistant-pi.service

Run from the Proxmox Agent project root:
  python deploy_banapi.py
"""
import os
import sys
import stat
import paramiko

# ── Connection ─────────────────────────────────────────────────────────────────
PI_IP   = os.getenv("PI_IP",   "192.168.0.235")
PI_PORT = int(os.getenv("PI_PORT", "22"))
PI_USER = "root"
PI_PASS = os.getenv("PI_PASS", "1234")   # banapi still uses password auth

# ── Paths ──────────────────────────────────────────────────────────────────────
REPO         = os.path.dirname(os.path.abspath(__file__))
SSH_KEYS_DIR = os.getenv("SSH_KEYS_DIR", r"D:\SSH Keys")

REMOTE_AGENT_DIR = "/home/pi/proxmox-agent"
REMOTE_KEYS_DIR  = "/root/.proxmox-agent/keys"
REMOTE_VENV      = f"{REMOTE_AGENT_DIR}/venv"

# Agent source files/dirs to upload
AGENT_FILES = [
    "main.py", "config.py", "llm.py", "ssh_client.py",
    "proxmox_api.py", "inventory.py", "patch.py", "backup.py",
    "pbs.py", "audit.py", "security.py", "onboarding.py", "tokens.py",
    "server.py", "requirements.txt",
]
# gui/ dir includes manifest.json now — handled by AGENT_DIRS upload
AGENT_DIRS = ["tools", "docs", "gui"]

# SSH key files to copy to the Pi
SSH_KEY_FILES = [
    "proxmox_id_ed25519",
    "debian_id_ed25519",
    "pihole_id_ed25519",
    "pihole-backup_id_ed25519",
    "heimdall_id_ed25519",
    "plex_id_ed25519",
    "pbs_id_ed25519",
    "homecloud_id_ed25519",
    "seeding_id_ed25519",
    "turnkey_id_ed25519",
]

PI_ENV = f"""\
# Proxmox agent .env — Pi runtime (auto-generated by deploy_banapi.py)
PROXMOX_HOST=192.168.0.91
PROXMOX_PORT=8006
PROXMOX_USER=root@pam
PROXMOX_PASS=

SSH_HOST=192.168.0.91
SSH_USER=root
SSH_KEY=proxmox_id_ed25519
SSH_KEYS_DIR={REMOTE_KEYS_DIR}

GUEST_KEY_turnkey-fileserver=turnkey_id_ed25519
GUEST_KEY_pihole=pihole_id_ed25519
GUEST_KEY_heimdall-dashboard=heimdall_id_ed25519
GUEST_KEY_pihole-backup=pihole-backup_id_ed25519
GUEST_KEY_plex=plex_id_ed25519
GUEST_KEY_proxmox-backup-server=pbs_id_ed25519
GUEST_KEY_debian=debian_id_ed25519
GUEST_KEY_homecloud=homecloud_id_ed25519
GUEST_KEY_seeding=seeding_id_ed25519

GUEST_IP_turnkey-fileserver=192.168.0.93
GUEST_IP_pihole=192.168.0.94
GUEST_IP_heimdall-dashboard=192.168.0.96
GUEST_IP_pihole-backup=192.168.0.99
GUEST_IP_plex=192.168.0.97
GUEST_IP_proxmox-backup-server=192.168.0.244
GUEST_IP_debian=192.168.0.81
GUEST_IP_homecloud=192.168.0.92
GUEST_IP_seeding=192.168.0.228

HA_URL=http://192.168.0.85:8123
BACKUP_STORAGE=local-pbs
BACKUP_MAX_AGE_H=24
STORAGE_WARN_PCT=80

# Set LLM_PROVIDER + API key to enable interactive mode
# LLM_PROVIDER=claude
# ANTHROPIC_API_KEY=sk-ant-...
# LLM_PROVIDER=openai
# OPENAI_API_KEY=sk-...
# LLM_PROVIDER=ollama
# OPENAI_BASE_URL=http://localhost:11434/v1
"""

SYSTEMD_SERVICE = f"""\
[Unit]
Description=Proxmox management agent (headless cron)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
User=root
WorkingDirectory={REMOTE_AGENT_DIR}
ExecStart={REMOTE_VENV}/bin/python main.py --no-llm
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""

SYSTEMD_TIMER = """\
[Unit]
Description=Run Proxmox agent headless check every 6 hours
Requires=proxmox-agent.service

[Timer]
OnCalendar=*-*-* 00,06,12,18:00:00
Persistent=true

[Install]
WantedBy=timers.target
"""

SYSTEMD_WEB = f"""\
[Unit]
Description=Proxmox Assistant web UI
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
WorkingDirectory={REMOTE_AGENT_DIR}
ExecStart={REMOTE_VENV}/bin/uvicorn server:app --host 0.0.0.0 --port 8080 --log-level warning
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


# ── Helpers ────────────────────────────────────────────────────────────────────

def run(ssh, cmd, check=True, timeout=120):
    print(f"  $ {cmd}")
    _, stdout, stderr = ssh.exec_command(cmd, get_pty=False, timeout=timeout)
    rc  = stdout.channel.recv_exit_status()
    out = stdout.read().decode(errors="replace").strip()
    err = stderr.read().decode(errors="replace").strip()
    if out:
        print(out.encode("ascii", errors="replace").decode("ascii"))
    if err and rc != 0:
        print(err.encode("ascii", errors="replace").decode("ascii"), file=sys.stderr)
    if check and rc != 0:
        print(f"[!] Command failed (exit {rc})", file=sys.stderr)
        sys.exit(1)
    return out


def mkdir_p(sftp, path):
    parts = [p for p in path.split("/") if p]
    cur = ""
    for p in parts:
        cur += "/" + p
        try:
            sftp.mkdir(cur)
        except OSError:
            pass  # already exists


def upload_dir(sftp, local_dir, remote_dir):
    skip = {"__pycache__", "venv", ".venv"}
    mkdir_p(sftp, remote_dir)
    for entry in os.scandir(local_dir):
        if entry.name in skip or entry.name.endswith(".pyc"):
            continue
        remote_path = remote_dir + "/" + entry.name
        if entry.is_dir():
            upload_dir(sftp, entry.path, remote_path)
        else:
            print(f"  upload {entry.path.replace(REPO, '.')} -> {remote_path}")
            sftp.put(entry.path, remote_path)


def upload_file(sftp, local_path, remote_path):
    print(f"  upload {os.path.basename(local_path)} -> {remote_path}")
    sftp.put(local_path, remote_path)


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print(f"Connecting to banapi ({PI_USER}@{PI_IP}:{PI_PORT}) ...")
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(PI_IP, port=PI_PORT, username=PI_USER, password=PI_PASS, timeout=20)
    print("Connected.\n")
    sftp = ssh.open_sftp()

    # 1. Create directories
    print("Creating directories ...")
    mkdir_p(sftp, REMOTE_AGENT_DIR)
    mkdir_p(sftp, REMOTE_KEYS_DIR)
    run(ssh, f"chown -R root:root {os.path.dirname(REMOTE_KEYS_DIR)}")
    run(ssh, f"chmod 700 {REMOTE_KEYS_DIR}")

    # 2. Upload agent source files
    print("\nUploading agent source ...")
    for fname in AGENT_FILES:
        local = os.path.join(REPO, fname)
        if os.path.exists(local):
            upload_file(sftp, local, f"{REMOTE_AGENT_DIR}/{fname}")
        else:
            print(f"  [skip] {fname} not found locally")

    for dname in AGENT_DIRS:
        local = os.path.join(REPO, dname)
        if os.path.isdir(local):
            upload_dir(sftp, local, f"{REMOTE_AGENT_DIR}/{dname}")

    # 3. Upload SSH keys
    print("\nUploading SSH keys ...")
    missing_keys = []
    for key_file in SSH_KEY_FILES:
        local = os.path.join(SSH_KEYS_DIR, key_file)
        if os.path.exists(local):
            remote = f"{REMOTE_KEYS_DIR}/{key_file}"
            upload_file(sftp, local, remote)
            sftp.chmod(remote, stat.S_IRUSR | stat.S_IWUSR)   # 0600
        else:
            missing_keys.append(key_file)
    if missing_keys:
        print(f"  [warn] keys not found locally: {', '.join(missing_keys)}")

    # 4. Write Pi-configured .env
    print("\nWriting .env ...")
    with sftp.open(f"{REMOTE_AGENT_DIR}/.env", "w") as f:
        f.write(PI_ENV)

    sftp.close()

    # 5. Python venv + dependencies
    print("\nSetting up Python venv ...")
    # Install numpy + system packages via apt (avoids building from source on 1GB ARM Pi)
    run(ssh, "apt-get install -y -qq python3 python3-pip python3-venv python3-numpy python3-dev", timeout=180)
    # --system-site-packages lets the venv use the system numpy directly
    run(ssh, f"python3 -m venv --system-site-packages {REMOTE_VENV}", timeout=60)
    run(ssh, f"{REMOTE_VENV}/bin/pip install -q --upgrade pip", timeout=60)
    run(ssh, f"{REMOTE_VENV}/bin/pip install -q paramiko", timeout=180)
    run(ssh, f"{REMOTE_VENV}/bin/pip install -q --no-deps rank_bm25", timeout=60)
    run(ssh, f"{REMOTE_VENV}/bin/pip install -q 'fastapi>=0.110' 'uvicorn[standard]>=0.29'", timeout=300)
    # anthropic is optional — install if LLM_PROVIDER=claude is desired
    run(ssh, f"{REMOTE_VENV}/bin/pip install -q anthropic || true", check=False, timeout=300)

    # 6. Fix permissions
    run(ssh, f"chown -R root:root {REMOTE_AGENT_DIR}")

    # 7a. Systemd headless service + timer (cron mode, every 6h)
    print("\nInstalling systemd service + timer (headless cron) ...")
    _write_remote(ssh, "/etc/systemd/system/proxmox-agent.service", SYSTEMD_SERVICE)
    _write_remote(ssh, "/etc/systemd/system/proxmox-agent.timer",   SYSTEMD_TIMER)

    # 7b. Systemd web UI service (persistent)
    print("Installing systemd web service ...")
    _write_remote(ssh, "/etc/systemd/system/proxmox-agent-web.service", SYSTEMD_WEB)

    run(ssh, "systemctl daemon-reload")
    run(ssh, "systemctl enable proxmox-agent.timer")
    run(ssh, "systemctl start proxmox-agent.timer")
    run(ssh, "systemctl enable proxmox-agent-web.service")
    run(ssh, "systemctl restart proxmox-agent-web.service")

    # 8. Build docs corpus (one-time, ~30s)
    print("\nBuilding Proxmox docs corpus (~30s) ...")
    run(ssh, f"cd {REMOTE_AGENT_DIR} && {REMOTE_VENV}/bin/python -m docs.scraper", check=False, timeout=120)

    # 9. Quick smoke test
    print("\nRunning smoke test ...")
    out = run(ssh, f"{REMOTE_VENV}/bin/python {REMOTE_AGENT_DIR}/main.py --no-llm", check=False, timeout=60)
    print(out[:1000] if out else "(no output)")

    # 10. Check web service started
    print("\nChecking web service ...")
    run(ssh, "systemctl is-active proxmox-agent-web.service", check=False)

    ssh.close()

    ip = PI_IP
    print("\n" + "=" * 60)
    print("Deploy complete.")
    print(f"  Agent dir  : {REMOTE_AGENT_DIR}")
    print(f"  Keys dir   : {REMOTE_KEYS_DIR}")
    print(f"  Web UI     : http://{ip}:8080   ← open this in a browser")
    print(f"  Cron timer : proxmox-agent.timer (headless check every 6h)")
    print()
    print("Next steps:")
    print(f"  1. Open http://{ip}:8080 in a browser")
    print(f"  2. Click ⚙ Settings -> set LLM_PROVIDER + API key")
    print(f"  3. Click 'Run a full health check' to onboard")
    print()
    print("To run interactively on banapi:")
    print(f"  ssh root@{ip}")
    print(f"  cd {REMOTE_AGENT_DIR}")
    print(f"  {REMOTE_VENV}/bin/python main.py")
    print()
    print("Web service logs:")
    print("  journalctl -u proxmox-agent-web -n 50 -f")
    print("  journalctl -u proxmox-agent -n 50")


def _write_remote(ssh, remote_path, content):
    sftp = ssh.open_sftp()
    with sftp.open(remote_path, "w") as f:
        f.write(content)
    sftp.close()


if __name__ == "__main__":
    main()
